-- Flor del Norte: esquema inicial.
-- Se corre una sola vez, entero, en Supabase > SQL Editor.

-- ============ Usuarios ============

create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default '',
  email text not null default '',
  rol text not null default 'vendedor' check (rol in ('admin', 'vendedor')),
  activo boolean not null default false,
  creado timestamptz not null default now()
);

-- security definer: las politicas consultan perfiles sin recursion de RLS
create or replace function public.es_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from perfiles where id = auth.uid() and rol = 'admin' and activo)
$$;

create or replace function public.es_activo() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from perfiles where id = auth.uid() and activo)
$$;

-- Al registrarse: el primer usuario queda admin activo; el resto espera que el admin lo apruebe
create or replace function public.crear_perfil() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  primero boolean;
begin
  select not exists (select 1 from perfiles) into primero;
  insert into perfiles (id, nombre, email, rol, activo)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nombre', ''),
    coalesce(new.email, ''),
    case when primero then 'admin' else 'vendedor' end,
    primero
  );
  return new;
end $$;

create trigger al_crear_usuario
  after insert on auth.users
  for each row execute function public.crear_perfil();

alter table public.perfiles enable row level security;

create policy "ver perfil propio o admin" on public.perfiles
  for select to authenticated using (id = auth.uid() or public.es_admin());

create policy "admin edita perfiles" on public.perfiles
  for update to authenticated using (public.es_admin()) with check (public.es_admin());

-- ============ Datos de la empresa (una sola fila) ============

create table public.empresa (
  id int primary key default 1 check (id = 1),
  datos jsonb not null default '{}'::jsonb,
  actualizado timestamptz not null default now()
);

insert into public.empresa (id) values (1);

alter table public.empresa enable row level security;

create policy "activos leen empresa" on public.empresa
  for select to authenticated using (public.es_activo());

create policy "admin edita empresa" on public.empresa
  for update to authenticated using (public.es_admin()) with check (public.es_admin());

-- ============ Presupuestos ============

create table public.presupuestos (
  numero bigint generated by default as identity primary key,
  creado timestamptz not null default now(),
  actualizado timestamptz not null default now(),
  vendedor_id uuid not null default auth.uid() references public.perfiles(id),
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'Aceptado', 'Rechazado', 'Vencido')),
  lista text not null check (lista in ('premium', 'mayorista')),
  descuento_pct numeric not null default 0,
  cliente jsonb not null default '{}'::jsonb,
  lineas jsonb not null default '[]'::jsonb,
  observaciones text not null default '',
  mensaje_original text not null default '',
  flete numeric not null default 0,
  iva_pct numeric not null default 0 check (iva_pct in (0, 10.5, 21)),
  -- productos con descuento, sin flete ni IVA; se guarda calculado para que los reportes no recalculen precios
  total numeric not null default 0
);

create index presupuestos_vendedor on public.presupuestos (vendedor_id);
create index presupuestos_creado on public.presupuestos (creado);

alter table public.presupuestos enable row level security;

-- Cada vendedor ve y edita lo suyo; el admin ve y edita todo
create policy "ver propios o admin" on public.presupuestos
  for select to authenticated
  using (public.es_activo() and (vendedor_id = auth.uid() or public.es_admin()));

create policy "crear propios" on public.presupuestos
  for insert to authenticated
  with check (public.es_activo() and vendedor_id = auth.uid());

create policy "editar propios o admin" on public.presupuestos
  for update to authenticated
  using (public.es_activo() and (vendedor_id = auth.uid() or public.es_admin()))
  with check (public.es_activo() and (vendedor_id = auth.uid() or public.es_admin()));

create policy "admin borra presupuestos" on public.presupuestos
  for delete to authenticated using (public.es_admin());

-- ============ Apodos aprendidos (compartidos por todos) ============

create table public.apodos (
  apodo text primary key,
  producto_id text not null,
  unidad text not null check (unidad in ('caja', 'bolsa')),
  ejemplo text not null default '',
  aprendido timestamptz not null default now(),
  creado_por uuid default auth.uid() references public.perfiles(id) on delete set null
);

alter table public.apodos enable row level security;

create policy "activos leen apodos" on public.apodos
  for select to authenticated using (public.es_activo());

create policy "activos crean apodos" on public.apodos
  for insert to authenticated with check (public.es_activo());

create policy "activos editan apodos" on public.apodos
  for update to authenticated using (public.es_activo()) with check (public.es_activo());

create policy "admin borra apodos" on public.apodos
  for delete to authenticated using (public.es_admin());

-- ============ Permisos de la API ============

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.perfiles, public.empresa, public.presupuestos, public.apodos to authenticated;
grant usage on all sequences in schema public to authenticated;
